### PR TITLE
ct support for adding materials

### PR DESCRIPTION
**Pull request by Trinsdar**
material addition part has been tested and is working, haven't tested adding flags yet, but theoretically it should work

### CODE REVIEW

**Comment by Trinsdar** [comment]
ok don't merge yet, I just got a crash from adding flags, it's because of this: 
```
if (flag.isCrafttweaker()){
			return Minecraft.getMinecraft().getTextureMapBlocks().getAtlasSprite(flag.getTexture());
		}
```

**Comment by Trinsdar** [comment]
ok crash is now fixed, though it will still crash if the texture can't be found, but there's nothing that can be done about that

**Comment by Trinsdar** [comment]
only question I have now is should the addition text for the overlay texture be 1 or overlay, or something else?

**Comment by Speiger** [comment]
@Trinsdar i would not suggest that since masks are limited to 64 Materials. That means if you register more then 64 you might encounter bugs.

**Comment by Trinsdar** [comment]
I am not sure what you mean, do you mean there can't be more then 64 flags, or that a material can't have more then 64 flags?

**Comment by Trinsdar** [comment]
ok talked it over with speiger in dms, nothing to worry about

**Comment by e99999** [comment]
i have an exception thrown if your register more than the limit, so yeah its fine.

**Comment by Speiger** [comment]
Yeah I missed that part. Just wanted to throw out concerns. xD

**Pull request merged**
